### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by postatum** [blakeembrey/server-address#6]
When using new popsicle-server (3+), I get 
```
     ReferenceError: self is not defined
      at ServerAddress.close (node_modules/server-address/dist/index.js:42:9)
      at /home/proj/node_modules/popsicle-server/dist/index.js:26:24
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/popsicle-server/dist/index.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Probably because of this line: https://github.com/blakeembrey/server-address/blob/master/src/index.ts#L49

**Comment by blakeembrey** [comment]
Thanks for the catch! Looks like it was missed because the DOM types are available in TypeScript and Jest. Fixed in https://github.com/blakeembrey/server-address/releases/tag/v3.0.1.

**Comment by postatum** [comment]
Thanks for fixing this! :green_apple:
